/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View } from 'react-native';
import { initAa2Sdk, getInfo, acceptAuthRequest, runAuth, checkIfCardWasRead, enterPin } from 'react-native-aa2-sdk';

export default class App extends Component<{}> {
  state = {
    status: 'starting',
    message: '--'
  };

  componentDidMount() {
    initAa2Sdk().then(init => {
      console.log({init})
      getInfo().then(info => {
        console.log({info})
        runAuth('https://test.governikus-eid.de/Autent-DemoApplication/RequestServlet?provider=demo_epa_20&redirect=true').then(auth => {
          console.log({auth})
          acceptAuthRequest().then(insertCard => {
            console.log({insertCard})
            checkIfCardWasRead().then(pinPrompt => {
              console.log({pinPrompt})
              enterPin(111111).then(pinAuthResponse => {
                console.log({pinAuthResponse})
              })
            })
          })
        })
      })
    })
  }

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆Aa2Sdk example☆</Text>
        <Text style={styles.instructions}>STATUS: {this.state.status}</Text>
        <Text style={styles.welcome}>☆NATIVE CALLBACK MESSAGE☆</Text>
        <Text style={styles.instructions}>{this.state.message}</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
